INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(1, '1648', '', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(2, 'Abbey Ales', 'Bath, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(3, 'Abbey Bells', 'Hirst Courtney, N Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(4, 'Abbeydale', 'Sheffield, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(5, 'Aberystwyth', 'Llanrhystyd, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(6, 'Ackhorne', 'York, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(7, 'Acorn', 'Wombwell, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(8, 'Adnams', 'Southwold, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(9, 'Albert Hotel', 'Douglas, Isle of Man', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(10, 'Albion', 'Loughborough, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(11, 'Alcazar', 'Old Basford, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(12, 'Alchemy', 'Hersham, Surrey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(13, 'Aldwincles', 'Fitzrovia, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(14, 'Ales of Kent', 'Chatham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(15, 'Ales of Scilly', 'St Marys, Scilly', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(16, 'Alford Arms', 'Frithsden, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(17, 'All Nations', 'Madeley, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(18, 'Alloa', 'Alloa, Clackmannanshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(19, 'An Teallach', 'Ullapool, Highlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(20, 'Ancient Druids', 'Cambridge', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(21, 'Anglo Dutch', 'Dewsbury, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(22, 'Archers', 'Swindon, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(23, 'Arkells', 'Swindon, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(24, 'Arran', 'Brodick, Isle of Arran', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(25, 'Arundel', 'Arundel, W. Sussex Castle', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(26, 'Ash Vine', 'Frome, Somerset Flammable L', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(27, 'Aston Manor', 'Aston, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(28, 'Atlas', 'Kinlochleven, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(29, 'Aviemore', 'Aviemore, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(30, 'Axminster', 'Axminster, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(31, 'Bacchus Bin', 'Stratford, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(32, 'Backdyke', 'Thornton, Fife, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(33, 'Badger', 'Blandford, Dorest', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(34, 'Bakers Arms', 'Leyton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(35, 'Bakery & Brewhouse', 'Oxford', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(36, 'Ballards', 'Rogate, West Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(37, 'Baltic Fleet', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(38, 'Banfield', 'Burrough on the Hill, Leics', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(39, 'Bank Top', 'Bolton, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(40, 'Banks', 'Wolverhampton, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(41, 'Banks & Taylor', 'Shefford Maidens Ret', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(42, 'Barge & Barrel', 'Elland, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(43, 'Barngates', 'Ambleside, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(44, 'Barnsley', 'Elescar, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(45, 'Bartrams', 'Thurston, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(46, 'Barum', 'Barnstaple, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(47, 'Bass', 'Burton, Staffs 1945 Commemora', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(48, 'Bass Museum', 'Burton-upon-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(49, 'Bateman', 'Wainfleet, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(50, 'Bath', 'Henstridge, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(51, 'Batham', 'Brierley Hill, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(52, 'Battersea', 'Battersea, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(53, 'Bazen', 'Salford, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(54, 'BBB', 'Blackburn, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(55, 'Beartown', 'Congleton, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(56, 'Becketts', 'Basingstoke, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(57, 'Beechams', 'St Helens, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(58, 'Beer Engine', 'Newton St. Cyres, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(59, 'Beer My Guest', 'Burton-on-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(60, 'Belhaven', 'Dunbar, Lothian, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(61, 'Bell Inn', 'Evercreech, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(62, 'Bells', 'Enderby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(63, 'Belvoir', 'Old Dalby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(64, 'Beowulf', 'Yardley, Birmingham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(65, 'Berkeley', 'Berkeley, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(66, 'Berrow', 'Burnham-on-Sea, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(67, 'Biddy Early', 'Inargh, Clare, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(68, 'Big End', 'Harrogate, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(69, 'Big Lamp', 'Newcastle, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(70, 'Big sheep', 'Bideford, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(71, 'Bird in Hand', 'Hayle, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(72, 'Bishops', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(73, 'Black Bull', 'Fenny Bentley, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(74, 'Black Dog', 'Whitby, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(75, 'Black Horse & Rainbow', 'Liverpool', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(76, 'Black Isle', 'Munlocky, Rossshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(77, 'Black Sheep', 'Masham, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(78, 'Blackawton', 'Washbourne, Totnes, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(79, 'Blackdown', 'Dunkeswell, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(80, 'Blackmoor', 'Batley, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(81, 'Blackpool', 'Blackpool, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(82, 'Blanchfield', 'Fakenham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(83, 'Blencowe', 'Barrowden, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(84, 'Blewitts', 'Kingsbridge, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(85, 'Blindmans', 'Leighton, Frome, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(86, 'Blue Anchor', 'Helston, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(87, 'Blue Bell', 'Whaplode St Catherine, Lincs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(88, 'Blue Cow', 'South Witham, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(89, 'Blue Moon', 'Barford, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(90, 'Blythe House', 'Rugeley, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(91, 'Boat', 'Castleford, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(92, 'Boddingtons', 'Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(93, 'Bodicote', 'Bodicote, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(94, 'Boggart Hole Clough', 'Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(95, 'Border', 'Tweedmouth, Berwick, Northumb.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(96, 'Borve', 'Ruthven, Huntley, Aberdeenshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(97, 'Bowland', 'Clitheroe, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(98, 'Box Steam', 'Box, Corsham, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(99, 'Bradleys', 'Dudley, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(100, 'Bragydy Ceredigion', 'Llangarog, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(101, 'Bragydy Ynys Mon', 'Talwrn, Anglesea', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(102, 'Brain', 'Cardiff, South Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(103, 'Brakspear', 'Henley-on-Thames, Oxon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(104, 'Bramcote', 'Bramcote, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(105, 'Brandy Cask', 'Pershore, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(106, 'Branscombe Vale', 'Branscombe, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(107, 'Bread & Roses', 'Clapham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(108, 'Brecknock', 'Swansea, Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(109, 'Breconshire', 'Brecon, Powys', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(110, 'Brewery on Sea', 'Lancing Round the M', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(111, 'Brewsters', 'Stathern, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(112, 'Bridge Inn', 'Dunham on Trent, Notts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(113, 'Bridge of Allan', 'Bridge of Allan, Cent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(114, 'Bridgewater', 'Goathurst, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(115, 'Briscoe', 'Otley, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(116, 'Bristol', 'Filton, Bristol', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(117, 'Bristol Beer Factory', 'Bedminster, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(118, 'British Oak', 'Eve Hill, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(119, 'Broadstone', 'Retford, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(120, 'Broughton', 'Broughton, Peeblesshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(121, 'Brown Cow', 'Barlow, Selby, N Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(122, 'Brunswick', 'Derby, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(123, 'Bryncelyn', 'Ystalyfera, West Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(124, 'Brysons', 'Heysham, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(125, 'Buffys', 'Tivetshall St. Mary, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(126, 'Bullmastiff', 'Leckwith, South Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(127, 'Buntingford', 'Buntingford, Herts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(128, 'Burrington', 'Burrington, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(129, 'BURTON', 'Burton-upon-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(130, 'Burton Bridge', 'Burton-on-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(131, 'Burtonwood', 'Burtonwood, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(132, 'Burts', 'Newport, Isle of Wight', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(133, 'Bury Street', 'Stowmarket, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(134, 'Bushys', 'Bradden, Isle of Man', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(135, 'Butcombe', 'Butcombe, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(136, 'Butterknowle', 'Butterknowle, Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(137, 'Butts', 'Great Shefford, Newbury, Berks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(138, 'Cains', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(139, 'Cairngorm', 'Aviemore, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(140, 'Caledonian', 'Edinburgh, Mid Lothian', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(141, 'Cambrian', 'Dolgellau, Gwynedd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(142, 'Cambridge Blue', 'Cambridge', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(143, 'Cambridge Moonshine', 'Cambridge, Cambs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(144, 'Cambrinus', 'Knowsley, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(145, 'Cameron', 'Hartlepool, Cleveland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(146, 'Camerons', 'Hartlepool, Cleveland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(147, 'CANNON', 'Sheffield, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(148, 'Cannon Royall', 'Uphampton, Worcs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(149, 'Canterbury', 'Canterbury, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(150, 'CAPE HILL', 'Birmingham, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(151, 'Captain Grumpys', 'Downham Market, Norf', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(152, 'Carlow', 'Carlow, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(153, 'Carpenters Arms', 'Marble Arch, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(154, 'Carters', 'Machen, Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(155, 'Cartmel', 'Kendal, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(156, 'Castle Eden', 'Castle Eden, Cleveland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(157, 'Castle Rock', 'Nottingham, Notts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(158, 'Catcher in the Rye', 'Finchley, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(159, 'Cathedrals', 'Durham, County Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(160, 'Chalk Hill', 'Norwich, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(161, 'Cheriton', 'Cheriton, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(162, 'Chiltern', 'Terrick, Buckinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(163, 'Church End', 'Shustoke, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(164, 'Church House', 'Holne, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(165, 'City of Cambridge', 'Cambridge, Cambs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(166, 'City of Stirling', 'Stirling, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(167, 'Clarks', 'Wakefield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(168, 'Clearwater', 'Torrington, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(169, 'Coach & Horses', 'Shrewsbury, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(170, 'Coach House', 'Warrington Cheshire Ca', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(171, 'Collingwood', 'Withersfield, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(172, 'Concertina', 'Mexborough, S. Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(173, 'Coniston', 'Coniston, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(174, 'Conwy', 'Conwy, Gwynedd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(175, 'Copper Dragon', 'Skipton, N Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(176, 'Cork & Cheese', 'Southend, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(177, 'Cornish', 'Redruth, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(178, 'Corvedale', 'Crofton, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(179, 'Cotleigh', 'Wiveliscombe Dragons T''A', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(180, 'Cottage', 'West Lydford, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(181, 'Cottage Spring', 'Cwmbran, Gewnt', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(182, 'Country Life', 'Westward Ho!, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(183, 'Courage', 'Bristol, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(184, 'Cox & Holbrook', 'Stowmarket, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(185, 'Cox Yard', 'Stratford on Avon, Warks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(186, 'Crockers', 'Maida Vale, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(187, 'Cropton', 'Pickering, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(188, 'Crouch Vale', 'Woodham Ferrers, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(189, 'Crown', 'Sheffield, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(190, 'Crown-Buckley', 'Llanelli, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(191, 'Cuckmere Haven', 'Exceat Bridge, E Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(192, 'Cwmbran', 'Cwmbran, Gwent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(193, 'Daleside', 'Starbeck, Harrogate, N Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(194, 'Dark Horse', 'Hertford, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(195, 'Dark Star', 'Brighton, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(196, 'Dark Tribe', 'Scunthorpe, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(197, 'Darwin', 'Sunderland, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(198, 'Davenports', 'Birmingham, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(199, 'Davys', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(200, 'Deeping', 'Market Deeping, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(201, 'Dent', 'Cowgill, Dent, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(202, 'Derby', 'Derby, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(203, 'Derwent', 'Consett, Co Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(204, 'Devon Ales', 'Sauchie, Alloa', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(205, 'Dog House', 'Redruth, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(206, 'Dolphin', 'Shrewsbury, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(207, 'Donnington', 'Stow-on-the-Wold, Gloucs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(208, 'Donoghue', 'Grainthorpe, Louth, Lincs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(209, 'Dorothys Bar', 'Weymouth, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(210, 'Dow Bridge', 'Catthorpe, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(211, 'Downton', 'Downton, Salisbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(212, 'Dublin', 'Dublin, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(213, 'Duke of Norfolk', 'Notting Hill, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(214, 'Dunn Plowman', 'Kington, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(215, 'Durham', 'Bowburn, County Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(216, 'Dwan', 'Thurles, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(217, 'Dyffryn Clwyd', 'Denbigh, Clwyd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(218, 'Earl Soham', 'Earl Soham, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(219, 'Easingwold', 'Easingwold, North Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(220, 'East Kent', 'Canterbury, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(221, 'Eastwood & Sanders', 'Luddendenfoot, W Y', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(222, 'Edale', 'Edale, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(223, 'Eldridge Pope', 'Dorchester, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(224, 'Elgoods', 'Wisbeach, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(225, 'Elveden', 'Elveden, Thetford, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(226, 'Enville Ales', 'Enville, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(227, 'Everards', 'Leicester, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(228, 'Evesham', 'Evesham, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(229, 'Exe Valley', 'Silverton, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(230, 'Exmoor', 'Wiveliscombe, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(231, 'Facers', 'Salford, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(232, 'Factotum & Firkin', 'Birmingham, W Mids', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(233, 'Fairway & Firkin', 'Blackheath, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(234, 'Faith & Firkin', 'Wandsworth Cmm, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(235, 'Falcon & Firkin', 'Homerton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(236, 'Falstaff', 'Derby, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(237, 'Fanfare & Firkin', 'Soho, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(238, 'Fantail & Firkin', 'Muswell Hill, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(239, 'Fantasy', 'Nuneaton, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(240, 'Faraday & Firkin', 'Clapham Junc, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(241, 'Farrier & Firkin', 'Marylebone, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(242, 'Fat God', 'Iron Cross, Evesham, Worcs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(243, 'Fates & Firkin', 'Bradford, W Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(244, 'Fatling & Firkin', 'Hornchurch, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(245, 'Faun & Firkin', 'Soho, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(246, 'Featherstone', 'Enderby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(247, 'Federation', 'Dunston, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(248, 'Feline & Firkin', 'Wolverhampton, W Mids', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(249, 'Felinfoel', 'Llanelli, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(250, 'Felix & Firkin', 'Barnet, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(251, 'Fellows', 'Morton & Clayton, Nottingham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(252, 'Felstar', 'Felsted, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(253, 'Fenland', 'Chatteris, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(254, 'Fernandes', 'Wakefield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(255, 'Ferret & Firkin', 'Chelsea, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(256, 'Fettler & Firkin', 'Paddington, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(257, 'Fewterer & Firkin', 'Sydenham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(258, 'Fiddle & Bone', 'Walsall, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(259, 'Fiddler & Firkin', 'Croydon, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(260, 'Fielder & Firkin', 'Sutton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(261, 'Financier & Firkin', 'Kingston, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(262, 'Finnock & Firkin', 'Islington, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(263, 'Fire Station', 'Waterloo, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(264, 'First In Last Out', 'Hastings, E Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(265, 'Fish & Firkin', 'Southend on Sea, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(266, 'Fisherman & Fikrin', 'Swansea, Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(267, 'Fisherrow', 'Edinburgh, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(268, 'Fitter & Firkin', 'Edinburgh, Lothian', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(269, 'Fitz & Firkin', 'Gt Portland St, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(270, 'Flagship', 'Chatham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(271, 'Flanker & Firkin', 'Coventry, West Mids', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(272, 'Flannerys', 'Aberystwyth, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(273, 'Flautist & Firkin', 'Mile End, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(274, 'Flicker & Firkin', 'Richmond, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(275, 'Flintlock & Firkin', 'Fitzrovia, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(276, 'Flock & Firkin', 'Dalston, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(277, 'Florin & Firkin', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(278, 'Flounder & Firkin', 'Highbury, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(279, 'Flourmill & Firkin', 'Brixton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(280, 'Flower & Firkin', 'Kew Gardens, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(281, 'Flute & Firkin', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(282, 'Flyman & Firkin', 'Covent Garden, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(283, 'Font & Firkin', 'Brighton, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(284, 'Foote & Firkin', 'Wandsworth, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(285, 'Footman & Firkin', 'Hendon, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(286, 'Ford & Firkin', 'Romford, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(287, 'Forger & Firkin', 'Guildford, Surrey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(288, 'Fornax & Firkin', 'South Harrow, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(289, 'Forster & Firkin', 'Blackfriars, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(290, 'Forth', 'Alloa, Clackmannanshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(291, 'Four Rivers', 'Hull, Humberside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(292, 'Fox', 'Heacham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(293, 'Fox & Firkin', 'Lewisham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(294, 'Fox & Newt', 'Leeds, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(295, 'Foxfield', 'Broughton in Furness, Cumb', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(296, 'Foxley', 'Mildenhall, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(297, 'Franciscan Well', 'Cork, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(298, 'Franklin & Firkin', 'Canterbury, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(299, 'Franklins', 'Harrogate, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(300, 'Frankton Bagby', 'Rugby, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(301, 'Freedom & Firkin', 'Tooting, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(302, 'Freeminer', 'Sling, Coleford, Gloucs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(303, 'Fresher & Firkin', 'Cambridge, Cambs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(304, 'Friar & Firkin', 'Euston, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(305, 'Friesian & Firkin', 'Clapham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(306, 'Frigate & Firkin', 'Olympia, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(307, 'Fringe & Firkin', 'Shepherd Bush, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(308, 'Fringilla & Firkin', 'Finchley, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(309, 'Frog & Firkin', 'Notting Hill, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(310, 'Frog & Parrot', 'Sheffield, S Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(311, 'Frog Island', 'Northampton, Northants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(312, 'Fromes Hill', 'Fromes Hill, Hereford', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(313, 'Frothfinders & Firkin', 'Pinner, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(314, 'Fugelstou', 'Louth, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(315, 'Fuggle & Firkin', 'Oxford, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(316, 'Full Mash', 'Stapleford, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(317, 'Fuller', 'Chiswick, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(318, 'Fulmar & Firkin', 'Holborn, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(319, 'Funnel & Firkin', 'Greenwich, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(320, 'Furgusons', 'Plympton, Plymouth, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(321, 'Furze & Firkin', 'Streatham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(322, 'Fusilier & Firkin', 'Camden Town, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(323, 'Fyfe', 'Kirkcaldy, Fife, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(324, 'Fyne', 'Inverary, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(325, 'Gales', 'Horndean, Portsmouth, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(326, 'Garden Barber', 'Bengeo, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(327, 'Garton', 'Driffield, East Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(328, 'George Inn', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(329, 'George Wright', 'Rainford, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(330, 'Gibbs Mew', 'Salisbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(331, 'Glastonbury', 'Somerton, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(332, 'Glentworth', 'Doncaster, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(333, 'Glossop', 'Hadfield, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(334, 'Goachers', 'Tovil, Maidstone, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(335, 'Goddards', 'Ryde, Isle of Wight', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(336, 'Goffs', 'Winchcombe, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(337, 'Golcar', 'Huddersfield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(338, 'Goldfinch', 'Dorchester, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(339, 'Goldthorn', 'Wolverhampton, W Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(340, 'Goodmanham', 'Goodmanham, East Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(341, 'Goose & Firkin', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(342, 'Goose Eye', 'Keighley, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(343, 'Grainstore', 'Oakham, Rutland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(344, 'Grand Union', 'Hayes, Middlesex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(345, 'Grays', 'Eccles, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(346, 'Great Western', 'Wolverhampton, W Mids', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(347, 'Green Tye', 'Much Hadham, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(348, 'Greene King', 'Bury St Edmunds, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(349, 'Greenfield', 'Greefield, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(350, 'Greenwoods', 'Wokingham, Berkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(351, 'Greyhound', 'Streatham Common, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(352, 'Gribble Inn', 'Oving, West Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(353, 'Grimsdales', '?????.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(354, 'Guernsey', 'St. Peter Port, Guernsey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(355, 'Guiness', 'Park Royal, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(356, 'Hadrian', 'Byker, Newcastle, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(357, 'Hadrian & Border', 'Newcastle, T & W', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(358, 'Haggard', 'Fulham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(359, 'Halifax Steam', 'Brighouse, West Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(360, 'Hallmark', 'Beccles, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(361, 'Halls', 'Oxford, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(362, 'Hambleton', 'Holme-on-Swale, N Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(363, 'Hampshire', 'Andover, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(364, 'Hanby Ales', 'Wem, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(365, 'Hanson', 'Dudley, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(366, 'Happy Hooker', 'Sleaford, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(367, 'Hardington', 'Bedminster, Bristol, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(368, 'Hardys & Hanson', 'Kimberley, Nottingham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(369, 'Hart', 'Little Eccleston, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(370, 'Harvey', 'Lewes, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(371, 'Harviestoun', 'Dollar, Clackmannanshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(372, 'Hawkshead', 'Hawkshead, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(373, 'Heather', 'Strathaven, Lanarkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(374, 'Hebridean', 'Isle of Lewis, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(375, 'Hedgehog & Hogshead', 'Fleet St, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(376, 'Hereward', 'Ely, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(377, 'Hesket Newmarket', 'Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(378, 'Hexhamshire', 'Ordly, Hexham, Northumb.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(379, 'Hidden', 'Dinton, Salisbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(380, 'High Force', 'Barnard Castle, Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(381, 'High House Farm', 'Matfen, Northumb', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(382, 'Highgate', 'Walsall, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(383, 'Highwood', 'Melton Ross, Humberside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(384, 'Hilden', 'Lisburn, Northern Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(385, 'Hill Island', 'Durham, Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(386, 'Hobdens', 'Warminster, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(387, 'Hobsons', 'Cleobury Mortimer, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(388, 'Hodges', 'Crook, County Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(389, 'Hoggleys', 'Kislingbury, Northants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(390, 'Hogs Back', 'Tongham, Surrey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(391, 'Holden', 'Woodsetton, Dudley, W Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(392, 'Holt', 'Cheetham, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(393, 'Home', 'Nottingham, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(394, 'Hook Norton', 'Hook Norton, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(395, 'Hop Back', 'Downton, Salisbury, Wilts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(396, 'Hopdaemon', 'Canterbury, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(397, 'Hopstar', 'Darwen, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(398, 'Hoskins', 'Leicester, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(399, 'Hoskins & Oldfield', 'Leicester, Leics', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(400, 'Hoskins Brothers', 'Leicester, Leics', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(401, 'Houston', 'Houston, Renfrewshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(402, 'Huddersfield', 'Huddersfield, West Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(403, 'Hull', 'Kingston-upon-Hull, Humberside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(404, 'Humpty Dumpty', 'Reedham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(405, 'Hydes', 'Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(406, 'Iceni', 'Ickburgh, Mundford, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(407, 'Ind Coope', 'Burton-upon-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(408, 'Inveralmond', 'Inveralmond, Perthshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(409, 'Isle of Man', 'Douglas, Isle of Man', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(410, 'Isle of Purbeck', 'Studland, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(411, 'Isle of Skye', 'Uig, Skye, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(412, 'Itchen Valley', 'Alresford, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(413, 'Jack Stamps', 'Streatham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(414, 'Jarrow', 'Jarrow, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(415, 'Jennings', 'Cockermouth, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(416, 'Jersey', 'St. Helier, Jersey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(417, 'John O''Gaunt', 'Somerby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(418, 'John Smith', 'Tadcaster, N Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(419, 'Jolly Boat', 'Bideford, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(420, 'Jolly Roger', 'Worcester, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(421, 'Joshua Tetley', 'Leeds, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(422, 'Joules', 'Stone, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(423, 'Judge', 'Rugby, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(424, 'Jurward', 'Wellington, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(425, 'Kelburn', 'Barrhead, Glasgow', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(426, 'Kelham Island', 'Sheffield, S Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(427, 'Keltek', 'Lostwithiel, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(428, 'Kemp Town', 'Brighton, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(429, 'Kent Garden', 'Faversham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(430, 'Khean', 'Congleton, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(431, 'King', 'Horsham, West Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(432, 'King & Barnes', 'Horsham, West Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(433, 'King Arthurs Arms', 'Tintagel, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(434, 'King William IV', 'Hampstead, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(435, 'Kings Arms', 'Hampton Court, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(436, 'Kings Head', 'Bildeston, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(437, 'Kitchen', 'Huddersfield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(438, 'Lamb & Flag', 'Oxford, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(439, 'Langton', 'East Langton, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(440, 'Larkins', 'Chiddingstone, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(441, 'Lass O''Gowrie', 'Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(442, 'Lastingham', 'Pickering, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(443, 'Leadmill', 'Selston, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(444, 'Leatherbritches', 'Fenny Bentley, Derbys', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(445, 'Ledbury', 'Ledbury, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(446, 'Leek', 'Leek, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(447, 'Lees', 'Middleton Junction, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(448, 'Les Sans-Culottes', 'Holborn, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(449, 'Leyden', 'Bury, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(450, 'Leyland', 'Wellingborough, Northants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(451, 'Lichfield', 'Lichfield, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(452, 'Lidstone', 'Wickhambrook, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(453, 'Linfit', 'Slaithwaite, Halifax, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(454, 'Lions', 'Burnley, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(455, 'Litten Tree', 'Old Street, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(456, 'Little Avenham', 'Preston, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(457, 'Litton', 'Skipton, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(458, 'Live & Let Live', 'Cambridge', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(459, 'Liverpool', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(460, 'Lloyds', 'Ingleby, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(461, 'Loddon', 'Reading, Berkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(462, 'London Beer Company', 'Hoxton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(463, 'Longstone', 'Belford, Northumberland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(464, 'Lord Nelson', 'Euston, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(465, 'Ma Pardoes', 'Netherton, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(466, 'Maclay', 'Alloa, Clackmannanshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(467, 'Maldon', 'Maldon, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(468, 'Mallard', 'Carlton, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(469, 'Malt & Hops', 'Kings Cross, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(470, 'Malton', 'Malton, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(471, 'Malvern Hills', 'Malvern, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(472, 'Mansfield', 'Mansfield, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(473, 'Marble', 'Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(474, 'Marches', 'Leominster, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(475, 'Market Porter', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(476, 'Marston', 'Burton-upon-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(477, 'Marston Moor', 'Kirk Hammerton, N Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(478, 'Mauldon', 'Sudbury, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(479, 'Mayflower', 'Standish, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(480, 'Mayhem', 'Apperley, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(481, 'Maypole', 'Eakring, Newark, Notts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(482, 'McGuiness', 'Rochdale, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(483, 'McMullen', 'Hertford, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(484, 'Meantime', 'Charlton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(485, 'Merlin', 'Leigh, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(486, 'Messers Maguire', 'Dublin, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(487, 'Middleton', 'Barnard Castle, Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(488, 'Mighty Oak', 'Brentwood, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(489, 'Mildmay', 'Holbeton, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(490, 'Milk Street', 'Frome, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(491, 'Millennium', '?', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(492, 'Millis', 'South Darenth, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(493, 'Millstone', 'Mossley, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(494, 'Milton', 'Milton, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(495, 'Miners Arms', 'Westbury-sub-Mendip, Som.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(496, 'Mitchell & Butler', 'Birmingham, W Mids.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(497, 'Mitchells', 'Lancaster, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(498, 'Moles', 'Bowerhill, Melksham, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(499, 'Moonstone', 'Burnley, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(500, 'Moor', 'Ashcott, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(501, 'Moorhouse', 'Burnley, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(502, 'Mordue', 'Shiremoor, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(503, 'Morland', 'Abingdon, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(504, 'Morrells', 'Oxford, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(505, 'Moulin', 'Pitlochry, Tayside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(506, 'Nelson', 'Chatham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(507, 'Nene Valley', 'Higham Ferrers, Northants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(508, 'Nethergate', 'Clare, Sudbury, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(509, 'Neuadd Arms', 'Llanwrtyd Wells, Powys', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(510, 'Newale', 'Andover, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(511, 'Newby Wyke', 'Little Bytham, Lincs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(512, 'Newmans', 'Banwell, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(513, 'North Downs', 'Dorking, Surrey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(514, 'North Star', 'Ealing, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(515, 'North Yorkshire', 'Middlesborough', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(516, 'Northern', 'Runcorn, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(517, 'Northumberland', 'Bedington, Northumb.', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(518, 'Nottingham', 'Radford, Nottinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(519, 'Nursery', 'Keynsham, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(520, 'Oakham', 'Peterborough, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(521, 'Oakhill', 'Oakhill, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(522, 'Oakleaf', 'Gosport, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(523, 'Oakwell', 'Barnsley, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(524, 'Odcome', 'Lower Odcombe, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(525, 'O''Hanlon', 'Clerkenwell, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(526, 'Old Bear', 'Cross Hills, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(527, 'Old Cannon', 'Bury St Edmunds, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(528, 'Old Chimneys', 'Market Weston, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(529, 'Old Cottage', 'Burton upon Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(530, 'Old Forge', 'Pett, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(531, 'Old Green Tree', 'Bath, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(532, 'Old Kent', 'Sevenoaks, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(533, 'Old Laxey', 'Old Laxey, Isle of Man', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(534, 'Old Malt Shovel', 'Newark, Notts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(535, 'Old Market Inn', 'Kettering, Northants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(536, 'Old Mill', 'Snaith, Goole, Humberside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(537, 'Old Priory', '???', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(538, 'Old Spot Inn', 'Dursley, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(539, 'Old Stables', 'Sandy, Bedfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(540, 'Oldershaw', 'Grantham, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(541, 'O''Malleys', 'Kilkenny, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(542, 'One Eyed Rat', 'Ripon, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(543, 'Orange', 'Pimlico, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(544, 'Orchard', 'Barnsley, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(545, 'Organic', 'Mullen, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(546, 'Orkney', 'Quoyloo, Orkney', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(547, 'Ossett', 'Ossett, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(548, 'Otter', 'Luppitt, Honiton, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(549, 'Oulton Ales', 'Oulton Broad, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(550, 'Owl', 'Oldham, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(551, 'Owl & Pussy Cat', 'Shoreditch, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(552, 'Oxenhope Moorland', 'Oxenhope, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(553, 'Oxford', 'Kidlington, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(554, 'Palmer', 'Bridport, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(555, 'Paradise', 'Nantwich, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(556, 'Parish', 'Somerby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(557, 'Passageway', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(558, 'Pembroke', 'Pembroke, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(559, 'Pembrokeshire Own Ales', 'Amroth, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(560, 'Phallanx & Firkin', 'York, N Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(561, 'Pharoah & Firkin', 'Fulham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(562, 'Pheasant & Firkin', 'Clerkenwell, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(563, 'Philanderer & Firkin', 'Oxford, Oxon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(564, 'Philatelist & Firkin', 'Bromley, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(565, 'Philomath & Firkin', 'Harrow, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(566, 'Philosopher & Firkin', 'Cowley, Oxford', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(567, 'Phoenix', 'Heywood, Greater Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(568, 'Phoenix & Firkin', 'Camberwell, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(569, 'Photographer & Firkin', 'Ealing, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(570, 'Picks', 'Accrington, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(571, 'Pictish', 'Rochdale, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(572, 'Pilgrim', 'Reigate, Bounty Ale', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(573, 'Pitfield', 'Hoxton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(574, 'Plassey', 'Eyton, Wrexham, Clwyd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(575, 'Poachers', 'Swinderby, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(576, 'Poole', 'Poole, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(577, 'Port Mahon', 'Sheffield, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(578, 'Portchester', 'Portchester, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(579, 'Porter', 'Haslingden, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(580, 'Porterhouse', 'Dublin, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(581, 'Potton', 'Potton, Bedfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(582, 'Premier Ales', 'Stourbridge, W Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(583, 'Princess Louise', 'Holborn, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(584, 'Princetown', 'Princetown, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(585, 'Pub With No Name', 'Priors Dean, Hants', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(586, 'Purple Moose', 'Porthmadog, Gwynedd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(587, 'Quadrant', 'Brighton, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(588, 'Quay', 'Weymouth, Dorset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(589, 'Queens Head', 'Aldham, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(590, 'Railway Tavern', 'Brightlingsea, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(591, 'Rainbow', 'Allesley, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(592, 'Ramsbottom', 'Ramsgate, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(593, 'Ramsgate', 'Ramsgate, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(594, 'Randalls', 'St. Peter Port, Guernsey', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(595, 'Rat & Ratchet', 'Huddersfield, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(596, 'Rayments', 'Furneaux Pelham, Herts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(597, 'RCH', 'Burnham-on-Sea, Somerset', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(598, 'Reading Lion', 'Reading, Berkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(599, 'Rebellion', 'Marlow, Buckinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(600, 'Reckless Erics', 'Pontypridd, Mid Glam', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(601, 'Rectory', 'Streat, Hassocks, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(602, 'Red Cross', 'Bromsgrove, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(603, 'Red Lion', 'Accrington, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(604, 'Red Rose', 'Great Harwood, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(605, 'Red Shoot', 'Ringwood, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(606, 'Red Squirrel', 'Hertford, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(607, 'Redruth', 'Redruth, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(608, 'Reepham', 'Reepham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(609, 'Reindeer', 'Norwich, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(610, 'Rhymney', 'Merthyr Tydfil, Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(611, 'Ridley', 'Hartford End, Chelmsf''d, Essex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(612, 'Ring O''Bells', 'Launceston, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(613, 'Ringwood', 'Ringwood, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(614, 'Rising Sun', 'Audley, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(615, 'Riverhead', 'Marsden, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(616, 'Riverside', 'Wainfleet All Saints, Lincs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(617, 'Robinson', 'Stockport, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(618, 'Robinwood', 'Todmorden, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(619, 'Rockingham', 'Elton, Cambridgeshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(620, 'Rooster', 'Harrogate, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(621, 'Rose Street', 'Edinburgh, Mid Lothian', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(622, 'Ross', 'Bishopston, Bristol, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(623, 'Rother Valley', 'Northiam, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(624, 'Royal Arms', 'Sutton Cheney, Leics', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(625, 'Ruddles', 'Langham, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(626, 'Rudgate', 'Tockwith, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(627, 'Ryburn', 'Sowerby Bridge, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(628, 'Saddleworth', 'Saddleworth, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(629, 'Salamander', 'Bradford, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(630, 'Salopian', 'Shrewsbury, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(631, 'Samuel Smith', 'Tadcaster, N. Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(632, 'Sarah Hughes', 'Sedgley, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(633, 'Sarahs Hophouse', 'Golborne, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(634, 'Sawbridgeworth', 'Sawbridgeworth, Herts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(635, 'Scanlon', 'Yiewsley, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(636, 'Scattor Rock', 'Christow, Exeter, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(637, 'Scottish & Newcastle', 'Edinburgh', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(638, 'Scotts', 'Lowestoft, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(639, 'Shardlow', 'Shardlow, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(640, 'Sharps', 'Wadebridge, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(641, 'Shaws', 'Dukinfield, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(642, 'Shepherd Neame', 'Faversham Gypsey Moth', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(643, 'Sherlock Holmes', 'Whitehall, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(644, 'Shires', 'Shefford, Bedfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(645, 'Six Bells', 'Bishops Castle, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(646, 'Skinners', 'Brighton, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(647, 'Slaters', 'Eccleshall, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(648, 'Slaughterhouse', 'Warwick, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(649, 'Smiles', 'Bristol, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(650, 'Snowdonia', 'Waunfawr, Gwynedd', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(651, 'SP Sporting', 'Stoke Prior, Herefords', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(652, 'Spectrum', 'Bradenham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(653, 'Spinning Dog', 'Hereford, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(654, 'Spread Eagle', 'Erpingham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(655, 'Springhead', 'Sutton on Trent, Notts', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(656, 'St Johns Tavern', 'Southwark, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(657, 'St. Austell', 'St. Austell, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(658, 'St. Georges', 'Callow End, Worcs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(659, 'St. Peters', 'South Elmham, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(660, 'Stag', 'Stotfold, Bedfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(661, 'Stanway', 'Stanway, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(662, 'Steam Packet', 'Knottingley, West Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(663, 'Steaming Billy', 'Oadby, Leicestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(664, 'Stocks', 'Doncaster, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(665, 'Stonecroft Inn', 'Llanwrtyd Wells, Powys', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(666, 'Stonehenge', 'Netheravon, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(667, 'Storm', 'Macclesfield, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(668, 'Stumpys', 'Hill Head, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(669, 'Sulwath', 'Kirkbean, Dumfries', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(670, 'Summerskills', 'Plymouth, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(671, 'Suthwyk', 'Southwick, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(672, 'Sutton', 'Plymouth, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(673, 'Swale', 'Sittingbourne, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(674, 'Swallow', 'Hillingdon, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(675, 'Swan', 'West Peckham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(676, 'Swansea', 'Bishopston, Swansea', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(677, 'Sweet William', 'Leyton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(678, 'Tarka', 'Instow, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(679, 'Taylor', 'Keighley, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(680, 'Teignworthy', 'Newton Abbot, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(681, 'Teme Valley', 'Knightwick, Worcs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(682, 'Tetley Walker', 'Warrington, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(683, 'Theakston', 'Masham, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(684, 'Thompsons', 'Ashburton, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(685, 'Three Rivers', 'Stockport, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(686, 'Three Tuns', 'Bishops Castle, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(687, 'Thwaites', 'Blackburn, Lancashire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(688, 'Tiger Tops', 'Wakefield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(689, 'Tilbury', 'Datchworth, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(690, 'Tindall', 'Ditchingham, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(691, 'Tipsy Toad', 'Jersey, Channel Islands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(692, 'Tirril', 'Tirril, Penrith, Cumbria', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(693, 'Tisbury', 'Tisbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(694, 'Titanic', 'Stoke-on-Trent, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(695, 'Tolly Cobbold', 'Ipswich, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(696, 'Tomintoul', 'Tomintoul, Banffshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(697, 'Tomlinson', 'Pontefract, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(698, 'Topsham & Exminster', 'Exminster, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(699, 'Tower', 'Burton-upon-Trent, Staffs', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(700, 'Town House', 'Audley, Staffordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(701, 'Townes', 'Chesterfield, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(702, 'Traquair House', 'Innerleithen, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(703, 'Trimdon', 'Trimdon, Durham', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(704, 'Tring', 'Tring, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(705, 'Tripple FFF', 'Alton, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(706, 'Trough', 'Idle, Bradford, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(707, 'Truemans', 'Medmenham, Buckinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(708, 'Truman', 'Shoreditch, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(709, 'Truscott', 'Liverpool Street, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(710, 'Tryst', 'Larbert, Stirlingshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(711, 'Tun', 'Vine & Press, Newnham, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(712, 'Twickenham', 'Twickenham, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(713, 'Uley', 'Dursley, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(714, 'ULU', 'Bloomsbury, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(715, 'Uncle Stuarts', 'Lingwood, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(716, 'Unicorn', '?????', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(717, 'University Tavern', 'Bloomsbury, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(718, 'Upper Agbrigg', 'Huddersfield, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(719, 'Ushers', 'Trowbridge, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(720, 'Vale', 'Haddenham, Buckinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(721, 'Valhalla', 'Baltasound, Unst, Shetland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(722, 'Vaux', 'Sunderland, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(723, 'Ventnor', 'Ventnor, Isle of Wight', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(724, 'Ventonwyn', 'Grampound Road, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(725, 'Verulam', 'St. Albans, Hertfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(726, 'Victoria', 'Woolton, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(727, 'Viking', 'Broadstairs, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(728, 'Vuax', 'Sunderland, Tyne & Wear', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(729, 'Wadworth', 'Devizes, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(730, 'Walshs Bakehouse', 'Warwick, Warwicks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(731, 'Waltham St Lawrence', 'WSL, Berkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(732, 'Wapping', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(733, 'Warcop', 'Wentlooge, Gwent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(734, 'Ward', 'Sheffield, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(735, 'Warrior', 'Brixton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(736, 'Warwickshire', 'Cubbington, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(737, 'Watermans Arms', 'Isle of Dogs, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(738, 'Watkins', 'Llandeilo, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(739, 'Waveney', 'Earsham, Suffolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(740, 'Weatheroak', 'Alvechurch, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(741, 'Webster & Wilson', 'Halifax, W Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(742, 'Weetwood', 'Weetwood, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(743, 'Well House', 'Exeter, Devon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(744, 'Wellington', 'Waterloo, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(745, 'Wells', 'Bedford, Bedfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(746, 'WELSH BREWERS', 'Cardiff, S Glamorgan', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(747, 'Weltons', 'Horsham, West Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(748, 'Wensleydale', 'Carlton, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(749, 'Wentworth', 'Wentworth, South Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(750, 'West Berkshire', 'Frilsham, Berkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(751, 'West Coast', 'Chorlton, Manchester', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(752, 'West Yorkshire', 'Luddendenfoot, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(753, 'Westbury', 'Westbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(754, 'Westerham', 'Edenbridge, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(755, 'Westminster Arms', 'Westminster, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(756, 'Wethered', 'Marlow, Buckinghamshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(757, 'Wetherspoons', 'London Century Ale', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(758, 'WF6', 'Altfots, Normanton, W Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(759, 'Whalebone', 'Hull, East Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(760, 'Wharfdale', 'Rylestone, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(761, 'Wharncliffe Arms', 'Tintagel, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(762, 'Whim', 'Hartington, Derbyshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(763, 'Whitbread', 'Cheltenham, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(764, 'Whitby', 'Whitby, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(765, 'White', 'Bexhill, East Sussex', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(766, 'White Horse', 'Stanford-i-t-Vale, Oxon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(767, 'White Star', 'Liverpool, Merseyside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(768, 'Whitewater', 'Kilkeel, Newry, Ireland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(769, 'Whitley Bridge', 'Wakefield, W Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(770, 'Whitstable', 'Whitstable, Kent', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(771, 'Whittington', 'Newent, Gloucestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(772, 'Wicked Hathern', 'Hathern, Leics', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(773, 'Wickwar', 'Wickwar, Avon', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(774, 'Wig & Gown', 'Holloway, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(775, 'Wild', 'Huddersfield, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(776, 'Wilds', 'Weobley, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(777, 'William Clark', 'Scarborough, N Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(778, 'William Greenwood', 'Thornton, W Yorks', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(779, 'William IV', 'Leyton, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(780, 'Williams', 'Carmarthen, Dyfed', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(781, 'Williams Brothers', 'Alloa, Scotland', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(782, 'Willys', 'Cleethorpes, Humberside', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(783, 'Wiltshire', 'Tisbury, Wiltshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(784, 'Winchester', 'Southampton, Hampshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(785, 'Winds of Change', 'S Petherwin, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(786, 'Windsor Castle', 'Lye, West Midlands', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(787, 'Winters', 'Norwich, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(788, 'Wishing Well', 'Dyke, Lincolnshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(789, 'Wizard', 'Whichford, Warwickshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(790, 'Wold Top', 'Driffield, East Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(791, 'Wolf', 'Attleborough, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(792, 'Wood', 'Wistanstow, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(793, 'Wooden Hand', 'Truro, Cornwall', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(794, 'Woodfordes', 'Woodbastwick, Norfolk', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(795, 'Woodhampton', 'Aymestry, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(796, 'Woodlands', 'Wrenbury, Cheshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(797, 'Worfield', 'Bridgnorth, Shropshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(798, 'Worth', 'Keighley, West Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(799, 'Wychwood', 'Witney, Oxfordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(800, 'wye Valley', 'Hereford, Herefordshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(801, 'Wylam', 'Heddon on the Wall, Northumb', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(802, 'Wyre Piddle', 'Fladbury, Worcestershire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(803, 'Yates', 'Ventnor, Isle of Wight', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(804, 'York', 'York, North Yorkshire', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(805, 'York Tavern', 'Islington, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(806, 'Yorkshire Grey', 'Holborn, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(807, 'Youngs', 'London Victory Ale', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(808, 'Ystwyth Ales', 'Capel Bangor, Wales', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(809, 'Zerodegrees', 'Blackheath, London', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(811, 'Purity', '', 1);
INSERT INTO `brewery_brewery` (`id`, `name`, `location`, `active`) VALUES(812, 'Pot Belly', '', 1);